services:
  web:
    image: ghcr.io/buddying-inc/webserver-centos83:apache24-php82
    container_name: bear-web
    working_dir: /var/www/html
    volumes:
      - type: bind
        source: ../source/app
        target: /var/www/html
        read_only: false
        consistency: delegated
      - type: bind
        source: localhost.conf
        target: /etc/httpd/conf.d/00_localhost.conf
        read_only: true
    ports:
      - "80:80"
    environment:
      - PHP_XDEBUG=off
      - COMPOSER_ALLOW_SUPERUSER=1
      - APP_ENV=local

  mysql:
    image: ghcr.io/buddying-inc/mysql:80
    container_name: bear-mysql
    volumes:
      - type: bind
        source: .mysql
        target: /var/lib/mysql
        read_only: false
        consistency: delegated
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=passw0rd
      - MYSQL_DATABASE=bear_db
      - MYSQL_USER=bear
      - MYSQL_PASSWORD=passw0rd
      - TZ=Asia/Tokyo

  sql-quality:
    image: ghcr.io/buddying-inc/mysql:80
    container_name: sql-quality
    volumes:
      - type: bind
        source: .sql-quality
        target: /var/lib/mysql
        read_only: false
        consistency: delegated
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=passw0rd
      - MYSQL_DATABASE=sql_quality_db
      - MYSQL_USER=sql_quality
      - MYSQL_PASSWORD=passw0rd
      - TZ=Asia/Tokyo

  smtp:
    image: mailhog/mailhog
    platform: linux/amd64
    container_name: bear-smtp
    ports:
      - "8025:8025"
      - "1025:1025"

#  localstack:
#    image: localstack/localstack
#    container_name: bear-aws
#    ports:
#      - "4566:4566"
#    volumes:
#      - ./localstack:/docker-entrypoint-initaws.d
#      - ./.localstack:/tmp/localstack:delegated
#    environment:
#      - DEFAULT_REGION=ap-northeast-1
#      - SERVICES=s3,sns
#      - DATA_DIR=/tmp/localstack/data
#      - DEBUG=1
#      - HOSTNAME_EXTERNAL=bear-aws
